config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  match "flower" => "flowers#flower", via: [:get, :post]
  match "flower/text" => "flowers#text", via: [:get, :post]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  respond_to :html, :js
  def flower
    if params[:pmid]
      begin
        @citation = PubMedApps::Citation.new params[:pmid]
        @related_json = @citation.to_json
      rescue ArgumentError => e
        @arg_error = "The PMID is invalid"
      end
    end
    if request.xhr?
      render json: @related_json
    end
  end

  def text
    if params[:pmid]
      begin
        @citation = PubMedApps::Citation.new params[:pmid]
        @citation.get_info # <= no test to confirm this line is here
        @related_citations = @citation.related_citations
      rescue ArgumentError => e
        @arg_error = "The PMID is invalid"
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  #
  # Eg., PubMedApps | Flower
  #
  # @param page_title [String] The title of the page
  #
  # @return [String] The nav bar title of the page
  def full_title page_title
    base_title = "PubMedApps"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/flowers/flower.html.slim
= javascript_include_tag "flower.js"
= javascript_include_tag "d3.v3.min.js"

- provide :title, "Flower"

.row
  h1 PubMed Flower

.row
  = form_tag controller: "flowers", action: "flower"
    = label_tag :pmid, "Enter PMID:"
    = text_field_tag :pmid
    = submit_tag "Blossom", class: "button radius tiny info"
    = link_to "Demo", flower_path(:pmid => "25313075"), :method => :post, class: "button radius tiny info"

- if @arg_error
  .row
    p = @arg_error
- elsif @citation && @related_json
  .row
    .small-7.large-7.columns#flowersvg
    .small-5.large-5.columns#flowertext
      h4#h4pmid
      p#pmid

      h4#h4title
      p#title

      h4#h4pubmedlink
      a#pubmedlink
    
      h4#h4abstract
      p#abstract
  javascript:
    jsondata = jQuery.parseJSON("#{j @related_json.html_safe}");
      rendering()

app/views/flowers/text.html.slim
- provide :title, "Flower (text only)"

.row
  h1 PubMed Flower (Text only)

.row
  = form_tag controller: "flowers", action: "text"
    = label_tag :pmid, "Enter PMID:"
    = text_field_tag :pmid
    = submit_tag "Blossom", class: "button radius tiny info"

-if @arg_error
  .row
    p = @arg_error
- elsif @citation
  .row  
    h2 Query
  .row
    .query
      h3 = @citation.title
      ul
        h4 Abstract
        - if @citation.abstract.nil? || @citation.abstract.empty?
          p Not available
        - else
          p = @citation.abstract
  .row
    h2 Related citations
  - @related_citations.each do |citation|
    .row
      .related
        h3 = link_to citation.title,
          controller: "flowers", action: "text", pmid: citation.pmid
        ul
          p
            | Score: 
            = citation.score
          h4 Abstract
          p = citation.abstract
      

app/views/layouts/_nav_bar.html.slim
.row
  nav.top-bar data-topbar="" role="navigation" 
    ul.title-area
      li.name
        h1
          = link_to "PubMedApps", root_path
      li.toggle-topbar.menu-icon
        a href="#" 
          span
    section.top-bar-section
      /! Right Nav Section
      ul.right
        li.divider
        li = link_to "Flower", flower_path
        li.divider
        li = link_to "Flower (text only)", flower_text_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= full_title yield :title %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.slim
- provide :title, ""

.row.top-pad
  = image_tag "pubmed_flower.svg", class: "center"